import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Header, Footer } from "@/components";
import { ThemeProvider } from "@/utils";
import Providers from './../../redux/Providers'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} min-w-[360px] overflow-x-hidden`}>
                <ThemeProvider>
                    <Providers>
                        <Header />
                        {children}
                        <Footer />
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    );
}
